<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAuthLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('auth_log');
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('rfid', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('success', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('attempt_timestamp', 'timestamp', null, array(
             'type' => 'timestamp',
             ));

        $this->option('symfony', array(
             'form' => false,
             ));
    }

}