<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('config');
        $this->hasColumn('config_key', 'string', 255, array(
             'type' => 'string',
             'primary' => true,
             'length' => '255',
             ));
        $this->hasColumn('config_value', 'clob', null, array(
             'type' => 'clob',
             ));

        $this->option('symfony', array(
             'filter' => false,
             'form' => false,
             ));
    }

}